logging:
  level:
    root: ERROR
spring:
  profiles:
    active: "dev"
  datasource:
    url: jdbc:h2:mem:mydb
    username: nubank
    password: ^s3cr37$
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false