logging:
  level:
    root: INFO
auth0:
  audience: https://ninjaone-rmm/api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-vph4ynx3.us.auth0.com/
  profiles:
    active: "dev"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
---
spring:
  profiles: "pro"
  datasource:
    url: jdbc:postgresql://ninjaone-rmm-db:5432/postgres
    username: postgres
    password: s3cr37n1nj40n3
    driverClassName: org.postgresql.Driver
---
spring:
  profiles: "dev"
  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    username: postgres
    password: s3cr37n1nj40n3
    driverClassName: org.h2.Driver
